### PR TITLE
Time slider

### LINKED ISSUE #23: Time slider
Not related to current date

### PR DESCRIPTION
**Pull request by hamishgibbs**
Added a time slider to replace time selection buttons. May be more of a hassle on mobile but I think we are far from being very mobile compatible anyways. 

Synchronises date filtering on all time series plots. This approach is not related to the current date and is therefore preferable to the past "Previous week approach". 

Internally, `activeTime` is now a date range `[minDate, maxDate]` rather than a string. 

This has cleaned up quite a few setups for buttons and individual interaction functions and hard coded date filtering so I hope it is an improvement.

Closes #23.

### CODE REVIEW

**Comment by seabbs** [comment]
Like the idea of a slider and can see how it might have a cleaner implementation. Agree on the potential mobile issue but I think just targeting desktop in general is absolutely fine and I imagine make life much easier.

**Comment by hamishgibbs** [comment]
That does make things easier. You can check out the new changes here: https://hamishgibbs.github.io/rt_vis/. Please let me know what you think.

There is a bit of work to do to merge this new version with RtD3 so it is not incorporated there yet.

There may be the same issue of it not being immediately apparent how to change the map datasets but clicking on the legend a few times works. We can discuss the best way to give the options without cluttering everything up.

**Comment by seabbs** [comment]
Looks really nice. Like the new selection ability for the map (might need some colour palette + scale tweaks).

I'm on mobile at the moment and the slider was really not that bad to use so that is good. Agree on needing to add some form of indication of what does what. Perhaps just some text indicating to people you can change mapped data/zoom the plots - though perhaps that can be done externally? 

Really excellent work 👍

**Comment by seabbs** [comment]
One comment (sorry this is not the correct place for it) when you zoom the X axis it would be great if the y axis changed dynamically. At the moment you can be looking at a section of the timeseries with 100 cases but the y axis is bounded at 20,000 (if this is not trivial can boot this down the road :) )

**Pull request merged**
